import React from 'react'
import '../src/styles/globals.css'
import Navigation from './components/navigation'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <head>
        <title>My first app</title>
      </head>
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  )
}
